/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package solutions.smartsecurity.contracts.health.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import solutions.smartsecurity.contracts.health.models.HealthRequest
import solutions.smartsecurity.contracts.health.models.HealthResponse

import com.squareup.moshi.Json

import solutions.smartsecurity.contracts.health.infrastructure.ApiClient
import solutions.smartsecurity.contracts.health.infrastructure.ApiResponse
import solutions.smartsecurity.contracts.health.infrastructure.ClientException
import solutions.smartsecurity.contracts.health.infrastructure.ClientError
import solutions.smartsecurity.contracts.health.infrastructure.ServerException
import solutions.smartsecurity.contracts.health.infrastructure.ServerError
import solutions.smartsecurity.contracts.health.infrastructure.MultiValueMap
import solutions.smartsecurity.contracts.health.infrastructure.PartConfig
import solutions.smartsecurity.contracts.health.infrastructure.RequestConfig
import solutions.smartsecurity.contracts.health.infrastructure.RequestMethod
import solutions.smartsecurity.contracts.health.infrastructure.ResponseType
import solutions.smartsecurity.contracts.health.infrastructure.Success
import solutions.smartsecurity.contracts.health.infrastructure.toMultiValue

class DefaultApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
     * POST /api/root/v1/health
     * Upload health beacon sample
     * 
     * @param healthRequest 
     * @return HealthResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiRootV1HealthPost(healthRequest: HealthRequest) : HealthResponse {
        val localVarResponse = apiRootV1HealthPostWithHttpInfo(healthRequest = healthRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as HealthResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/root/v1/health
     * Upload health beacon sample
     * 
     * @param healthRequest 
     * @return ApiResponse<HealthResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun apiRootV1HealthPostWithHttpInfo(healthRequest: HealthRequest) : ApiResponse<HealthResponse?> {
        val localVariableConfig = apiRootV1HealthPostRequestConfig(healthRequest = healthRequest)

        return request<HealthRequest, HealthResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiRootV1HealthPost
     *
     * @param healthRequest 
     * @return RequestConfig
     */
    fun apiRootV1HealthPostRequestConfig(healthRequest: HealthRequest) : RequestConfig<HealthRequest> {
        val localVariableBody = healthRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/root/v1/health",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
