/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package solutions.smartsecurity.contracts.health.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import solutions.smartsecurity.contracts.health.apis.DefaultApi
import solutions.smartsecurity.contracts.health.models.HealthRequest
import solutions.smartsecurity.contracts.health.models.HealthResponse

class DefaultApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DefaultApi
        //val apiInstance = DefaultApi()

        // to test apiRootV1HealthPost
        should("test apiRootV1HealthPost") {
            // uncomment below to test apiRootV1HealthPost
            //val healthRequest : HealthRequest =  // HealthRequest | 
            //val result : HealthResponse = apiInstance.apiRootV1HealthPost(healthRequest)
            //result shouldBe ("TODO")
        }

    }
}
