/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package solutions.smartsecurity.contracts.health.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param deviceId 
 * @param timestamp 
 * @param batteryPercent 
 * @param lteRssi 
 * @param wifiRssi 
 */


data class HealthRequest (

    @Json(name = "deviceId")
    val deviceId: kotlin.String,

    @Json(name = "timestamp")
    val timestamp: java.time.OffsetDateTime,

    @Json(name = "batteryPercent")
    val batteryPercent: kotlin.Int,

    @Json(name = "lteRssi")
    val lteRssi: kotlin.Int,

    @Json(name = "wifiRssi")
    val wifiRssi: kotlin.Int

) {


}

