/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package solutions.smartsecurity.contracts.health.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import solutions.smartsecurity.contracts.health.models.HealthRequest

class HealthRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of HealthRequest
        //val modelInstance = HealthRequest()

        // to test the property `deviceId`
        should("test deviceId") {
            // uncomment below to test the property
            //modelInstance.deviceId shouldBe ("TODO")
        }

        // to test the property `timestamp`
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

        // to test the property `batteryPercent`
        should("test batteryPercent") {
            // uncomment below to test the property
            //modelInstance.batteryPercent shouldBe ("TODO")
        }

        // to test the property `lteRssi`
        should("test lteRssi") {
            // uncomment below to test the property
            //modelInstance.lteRssi shouldBe ("TODO")
        }

        // to test the property `wifiRssi`
        should("test wifiRssi") {
            // uncomment below to test the property
            //modelInstance.wifiRssi shouldBe ("TODO")
        }

    }
}
