/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package solutions.smartsecurity.contracts.health.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import solutions.smartsecurity.contracts.health.models.HealthResponse

class HealthResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of HealthResponse
        //val modelInstance = HealthResponse()

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

    }
}
